name: 'GitHub CI'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache local Maven repository
      uses: actions/cache@v2.1.4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      env:
        BROWSER: chrome-container
      run: mvn -V -ntp clean verify --file pom.xml '-Djenkins.test.timeout=5000' '-Dgpg.skip'
    - name: Autograding
      uses: uhafner/autograding-github-action@v1.6.0
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HEAD_SHA: ${{github.event.pull_request.head.sha}}
        CONFIG: >
          {
            "analysis": {
              "maxScore": 100,
              "errorImpact": -5,
              "highImpact": -2,
              "normalImpact": -1,
              "lowImpact": -1
            },
            "tests": {
              "maxScore": 100,
              "failureImpact": -10,
            },
            "coverage": {
              "maxScore": 100,
              "missedPercentageImpact": -1
            },
            "pit": {
              "maxScore": 100,
              "undetectedPercentageImpact": -1
            }
          }
